apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: automationhub-dev
  namespace: ansible-automation-platform
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  file_storage_size: 100Gi
  image_pull_policy: IfNotPresent
  object_storage_s3_secret: s3-secret-automationhub-dev
  web:
    replicas: 1
  file_storage_access_mode: ReadWriteMany
  content:
    log_level: INFO
    replicas: 2
  postgres_storage_requirements:
    limits:
      storage: 50Gi
    requests:
      storage: 8Gi
  api:
    log_level: INFO
    replicas: 1
  postgres_resource_requirements:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 2Gi
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
  # route_host: automationhub-dev.apps.cluster-7987.sandbox19.opentlc.com
  storage_type: S3
  worker:
    replicas: 2

