apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ansible-automation-platform-og.yaml
- ansible-automation-platform-operator-sub.yaml
- ansible-automation-platform-ns.yaml
